# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-04 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipfrom', models.CharField(help_text='shipfrom', max_length=512, null=True)),
                ('Shipto', models.CharField(help_text='shipto', max_length=512, null=True)),
                ('PO', models.CharField(help_text='PO', max_length=512, null=True)),
                ('Forwarder', models.CharField(help_text='Forwarder', max_length=512, null=True)),
                ('SN', models.CharField(help_text='SN', max_length=512, null=True)),
                ('Packages', models.IntegerField(help_text='Packages', null=True)),
                ('ProductDescription', models.CharField(help_text='ProductDescription', max_length=512, null=True)),
                ('Qty', models.IntegerField(help_text='Qty', null=True)),
                ('receiveQty', models.IntegerField(help_text='receiveQty', null=True)),
                ('submitButton', models.CharField(default='NO', help_text='submitButton', max_length=512)),
                ('receiveButton', models.CharField(default='NO', help_text='receiveButton', max_length=512)),
                ('NO', models.IntegerField(help_text='NO', null=True)),
                ('NetWeight', models.CharField(help_text='NetWeight', max_length=512)),
                ('GrossWeight', models.CharField(help_text='GrossWeight', max_length=512)),
                ('Volume', models.CharField(help_text='Volume', max_length=512)),
                ('Tracking', models.CharField(help_text='Tracking', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Contact', models.EmailField(help_text='Contact', max_length=254, null=True)),
                ('Phone', models.CharField(help_text='Phone', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(help_text='orderId', max_length=512)),
                ('ordersubmitButton', models.CharField(default='NO', help_text='ordersubmitButton', max_length=512)),
                ('orderreceiveButton', models.CharField(default='NO', help_text='orderreceiveButton', max_length=512)),
                ('vendorcomments', models.CharField(help_text='vendorcomments', max_length=512, null=True)),
                ('receivecommets', models.CharField(help_text='receivecommets', max_length=512, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='people')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='orderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collec.Order', verbose_name='orderID'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sender'),
        ),
    ]
