# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Forwarder',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='GrossWeight',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='NO',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='NetWeight',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='PO',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Packages',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Shipfrom',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Shipto',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Tracking',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='Volume',
        ),
        migrations.AddField(
            model_name='asset',
            name='PartNo',
            field=models.CharField(help_text='PartNo', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Forwarder',
            field=models.CharField(help_text='Forwarder', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='GrossWeight',
            field=models.CharField(default=201807091025L, help_text='GrossWeight', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='NetWeight',
            field=models.CharField(default=django.utils.timezone.now, help_text='NetWeight', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='PO',
            field=models.CharField(help_text='PO', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Packages',
            field=models.IntegerField(help_text='Packages', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipfrom',
            field=models.CharField(help_text='shipfrom', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Shipto',
            field=models.CharField(help_text='shipto', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Tracking',
            field=models.CharField(default=1111111111, help_text='Tracking', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Volume',
            field=models.CharField(default=django.utils.timezone.now, help_text='Volume', max_length=512),
            preserve_default=False,
        ),
    ]
