# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-07-30 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0002_auto_20180709_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiveOrder_time',
            field=models.DateTimeField(help_text='receive_Order_time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_vendor_comment',
            field=models.CharField(default='NO', help_text='receive_vendor_comment', max_length=512),
        ),
        migrations.AddField(
            model_name='order',
            name='sendOrder_time',
            field=models.DateTimeField(help_text='send_Order_time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='send_vendor_comment',
            field=models.CharField(default='NO', help_text='send_vendor_comment', max_length=512),
        ),
    ]
