# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0003_auto_20180730_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_Order_time',
            field=models.DateTimeField(help_text='create_Order_time', null=True),
        ),
    ]
