# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-08-10 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('collec', '0004_order_create_order_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Phone', models.CharField(help_text='Phone', max_length=255, null=True)),
                ('clear_password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='Contact',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='Phone',
            field=models.CharField(max_length=255),
        ),
    ]
