# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0005_auto_20180810_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Category',
            field=models.CharField(help_text='Category', max_length=512, null=True),
        ),
    ]
