# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-05 14:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0006_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='City',
            field=models.CharField(help_text='City', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='Country',
            field=models.CharField(help_text='Country', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extenduser',
            name='Email',
            field=models.EmailField(help_text='Email', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='receive_user',
            field=models.CharField(default=1, max_length=512, verbose_name='receive_user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='sent_user'),
        ),
    ]
