# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-06 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0007_auto_20180905_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='User_Status',
            field=models.CharField(default='vendor', max_length=255, null=True),
        ),
    ]
