# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-07 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collec', '0008_extenduser_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='content', max_length=255, null=True)),
            ],
        ),
    ]
